[workspace]
members = [
  "examples/embed",
  "examples/importer",
  "beetle",
  "beetle-api",
  "beetle-bitswap",
  "beetle-car",
  "beetle-embed",
  "beetle-gateway",
  "beetle-localops",
  "beetle-metrics",
  "beetle-one",
  "beetle-p2p",
  "beetle-resolver",
  "beetle-rpc-client",
  "beetle-rpc-types",
  "beetle-share",
  "beetle-unixfs",
  "beetle-store",
  "beetle-util",
  "xtask",
]
# even if all crates are set to edition 2021, we still need to force the
# resolver to 2
# https://github.com/gfx-rs/wgpu/issues/2356#issuecomment-1005134986
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "Apache-2.0/MIT"
rust-version = "1.65"
repository = "https://github.com/n0-computer/beetle"

[workspace.dependencies]
# We prefer to place all dependencies for our workspace crates here.
# The should be added here with default features only so that each
# crate explicitly enables the features they need.
#
# There are two execeptions to this:
# - If a crate needs a dependency with `default-features=false` the
#   default features must be disabled here.
# - If we really want to uniformely enforce a feature in all crates,
#   e.g. anyhow's backtrace feature.

ahash = "0.8"
anyhow = { version = "1", features = ["backtrace"] }
async-broadcast = "0.4.1"
async-channel = "1.7.1"
async-recursion = "1"
async-stream = "0.3.3"
async-trait = "0.1.57"
asynchronous-codec = "0.6"
axum = "0.6"
backoff = "0.4"
base64 = "0.20.0"
bincode = "1.3.3"
bs58 = "0.4"
bytecheck = "0.6.7"
bytes = "1.1"
bytesize = "1.1"
cid = "0.9"
clap = "4.0.15"
clap_mangen = "0.2.2"
config = "0.13.1"
console = { version = "0.15", default-features = false }
console-subscriber = "0.1.7"
criterion = "0.4"
crossterm = "0.25"
ctrlc = "3.2.2"
deadqueue = "0.2.3"
derivative = "2.2"
derive_more = "0.99.17"
dirs-next = "2"
fastmurmur3 = "0.1.2"
fnv = "1.0.7"
futures = "0.3.24"
futures-util = "0.3.21"
git-version = "0.3.5"
handlebars = "4"
headers = "0.3.7"
hex = "0.4.3"
hex-literal = "0.3.4"
http = "0.2"
http-body = "0.4.5"
http-serde = "1.1"
humansize = "2"
hyper = "0.14.23"
ignore = "0.4.18"
indicatif = "0.17.1"
integer-encoding = "3.0"
beetle = { version = "0.2.0", path = "./beetle" }
beetle-api = { version = "0.2.0", path = "./beetle-api" }
beetle-bitswap = { version = "0.2.0", path = "./beetle-bitswap" }
beetle-car = { version = "0.2.0", path = "./beetle-car" }
beetle-embed = { version = "0.2.0", path = "./beetle-embed" }
beetle-gateway = { version = "0.2.0", path = "./beetle-gateway" }
beetle-localops = { version = "0.2.0", path = "./beetle-localops" }
beetle-metrics = { version = "0.2.0", path = "./beetle-metrics" }
beetle-one = { version = "0.2.0", path = "./beetle-one" }
beetle-p2p = { version = "0.2.0", path = "./beetle-p2p" }
beetle-resolver = { version = "0.2.0", path = "./beetle-resolver" }
beetle-rpc-client = { version = "0.2.0", path = "./beetle-rpc-client" }
beetle-rpc-types = { version = "0.2.0", path = "./beetle-rpc-types" }
beetle-store = { version = "0.2.0", path = "./beetle-store" }
beetle-unixfs = { version = "0.2.0", path = "./beetle-unixfs" }
beetle-util = { version = "0.2.0", path = "./beetle-util" }
keyed_priority_queue = "0.4.1"
lazy_static = "1.4"
libipld = "0.15"
libp2p = { version = "0.50", default-features = false }
lru = "0.8"
mime = "0.3"
mime_classifier = "0.0.1"
mime_guess = "2.0.4"
multibase = "0.9.1"
multihash = "0.17"
names = { version = "0.14.0", default-features = false }
nix = "0.26"
num_enum = "0.5.7"
once_cell = "1.15"
opentelemetry = "0.18"
opentelemetry-otlp = "0.11"
par-stream = { version = "0.10.2", default-features = false }
paste = "1.0.9"
phf = "0.11"
prometheus-client = "0.18"
proptest = "1"
prost = "0.11"
prost-build = "0.11.1"
quic-rpc = { version = "0.3.2", default-features = false }
rand = "0.8.5"
rand_chacha = "0.3.1"
rayon = "1.5.3"
relative-path = "1.7.2"
reqwest = { version = "0.11.10", default-features = false}
rkyv = "0.7.37"
rlimit = "0.9.0"
rocksdb = "0.19"
ruzstd = "0.3"
serde = "1"
serde-error = "0.1.2"
serde_json = "1.0.87"
serde_qs = "0.10.1"
serde_with = "2.1"
sha2 = { version = "0.10", default-features = false }
smallvec = "1.10"
ssh-key = { version = "0.5.1", default-features = false }
sysinfo = "0.27.2"
temp-env = "0.3.1"
tempfile = "3.3"
testdir = "0.7.0"
thiserror = "1"
time = "0.3.9"
tokio = "1"
tokio-context = "0.1.3"
tokio-stream = "0.1.11"
tokio-test = "0.4.2"
tokio-util = "0.7"
toml = "0.5.9"
tower = "0.4"
tower-http = "0.3"
tower-layer = "0.3"
tracing = "0.1.34"
tracing-opentelemetry = "0.18"
tracing-subscriber = "0.3.14"
trust-dns-resolver = "0.22.0"
unsigned-varint = "0.7.1"
url = "2.2.2"
urlencoding = "2.1"
wasm-timer = "0.2.5"
which = "4.3.0"
xtaskops = "0.3"
zeroize = "1.4"

[profile.optimized-release]
inherits = 'release'
lto = true
debug = false
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false

[profile.docker]
inherits = 'release'
lto = true
debug = false
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false

[workspace.metadata.release]
consolidate-commits = true
