[package]
name = "xtask"
version.workspace = true
edition.workspace = true
publish = false
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
clap_mangen.workspace = true
dirs-next.workspace = true
xtaskops.workspace = true
beetle.workspace = true
