# this is a standard, bare bones beetle configuration. More sophisticated setups
# will take advantage of metrics, and provide custom configuration
#
# Usage:
# run 'docker-compose up' from the docker directory, use 'beetle status' from
# another terminal to interact with services, or visit localhost:9050 on a
# browser to utilize the gateway
version: "3.9"
services:
  beetle-gateway:
    container_name: "beetle-gateway"
    image: "n0computer/beetle-gateway:latest"
    environment:
      - "BEETLE_GATEWAY__RPC_CLIENT__P2P_ADDR=grpc://beetle-p2p:4401"
      - "BEETLE_GATEWAY__RPC_CLIENT__STORE_ADDR=grpc://beetle-store:4402"
    ports:
      # public HTTP gateway port. eg: http://localhost:9050/ipfs/bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi
      - "9050:9050"
      # RPC port, beetle CLI uses this to control your gateway service
      # this shouldn't be publically accessible, so we explicitly wire it
      # to the local loopback address: 127.0.0.1
      - "127.0.0.1:4400:4400"
  beetle-p2p:
    container_name: "beetle-p2p"
    image: "n0computer/beetle-p2p:latest"
    environment:
      - "BEETLE_P2P__RPC_CLIENT__STORE_ADDR=grpc://beetle-store:4402"
    ports:
      # libp2p connection port. peers will dial your node here
      - "4444:4444"
      # RPC port, beetle CLI uses this to control your p2p service
      # this shouldn't be publically accessible, so we explicitly wire it
      # to the local loopback address: 127.0.0.1
      - "127.0.0.1:4401:4401"
  beetle-store:
    container_name: "beetle-store"
    image: "n0computer/beetle-store:latest"
    ports:
      # RPC port, beetle CLI uses this to control your store service
      # this shouldn't be publically accessible, so we explicitly wire it
      # to the local loopback address: 127.0.0.1
      - "127.0.0.1:4402:4402"