[package]
name = "beetle-resolver"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
description = "Implementation of path resolution for beetle"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

exclude = [
  "tests/**",
  "fixtures/**",
]

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
async-stream.workspace = true
async-trait.workspace = true
bs58.workspace = true
bytes.workspace = true
cid.workspace = true
futures.workspace = true
beetle-metrics = { workspace = true, features = ["resolver", "gateway"] }
beetle-rpc-client.workspace = true
beetle-util.workspace = true
beetle-unixfs.workspace = true
libipld.workspace = true
libp2p.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["fs"] }
tracing.workspace = true
trust-dns-resolver = { workspace = true, features = ["dns-over-https-rustls", "serde-config", "tokio-runtime"] }
fnv.workspace = true

[dev-dependencies]
beetle-car.workspace = true
beetle-rpc-types.workspace = true
beetle-store.workspace = true
proptest.workspace = true
rand.workspace = true
async-recursion.workspace = true
rand_chacha.workspace = true
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread", "fs"] }
ruzstd.workspace = true
